{
 "title": "NSE Comparison Charts",
 "time": { "from": "2020-01-07T20:50:58.000Z", "to": "2021-05-11T19:04:36.000Z" },
 "panels": [
  {
   "title": "3MINDIA",
   "type": "ilgizar-candlestick-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  \n  date_trunc('day', date1) as time,\n  (array_agg(open_price ORDER BY date1 ASC))[1] as open,\n  MAX(high_price) as high,\n  MIN(low_price) as low,\n  (array_agg(close_price ORDER BY date1 DESC))[1] as close,\n  SUM(no_of_trades) as volume\nFROM bhavdata\nWHERE date1 BETWEEN (SELECT min(date1) FROM bhavdata) AND (SELECT max(date1) FROM bhavdata) AND symbol='3MINDIA'\nGROUP BY date1"
    }
   ]
  },
  {
   "title": "TCS",
   "type": "ilgizar-candlestick-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT  \n  date_trunc('day', date1) as time,\n  (array_agg(open_price ORDER BY date1 ASC))[1] as open,\n  MAX(high_price) as high,\n  MIN(low_price) as low,\n  (array_agg(close_price ORDER BY date1 DESC))[1] as close,\n  SUM(no_of_trades) as volume\nFROM bhavdata\nWHERE date1 BETWEEN (SELECT min(date1) FROM bhavdata) AND (SELECT max(date1) FROM bhavdata) AND symbol='TCS'\nGROUP BY date1"
    }
   ]
  },
  {
   "title": "Total NSE Data",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date1 AS \"time\",\n  symbol AS metric,\n  avg_price\nFROM bhavdata\nWHERE\n  $__timeFilter(date1)\nORDER BY 1,2"
    }
   ]
  }
 ]
}